// Mocks generated by Mockito 5.4.4 from annotations
// in horcrux/test/services/backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:horcrux/models/backup_status.dart' as _i8;
import 'package:horcrux/models/event_status.dart' as _i12;
import 'package:horcrux/models/recovery_request.dart' as _i10;
import 'package:horcrux/models/relay_configuration.dart' as _i16;
import 'package:horcrux/models/steward_status.dart' as _i9;
import 'package:horcrux/models/vault.dart' as _i7;
import 'package:horcrux/providers/vault_provider.dart' as _i5;
import 'package:horcrux/services/login_service.dart' as _i14;
import 'package:horcrux/services/ndk_service.dart' as _i3;
import 'package:horcrux/services/relay_scan_service.dart' as _i4;
import 'package:horcrux/services/shard_distribution_service.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:ndk/ndk.dart' as _i13;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyPair_0 extends _i1.SmartFake implements _i2.KeyPair {
  _FakeKeyPair_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeNdkService_1 extends _i1.SmartFake implements _i3.NdkService {
  _FakeNdkService_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeScanningStatus_2 extends _i1.SmartFake implements _i4.ScanningStatus {
  _FakeScanningStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultRepository extends _i1.Mock implements _i5.VaultRepository {
  MockVaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i7.Vault>> get vaultsStream =>
      (super.noSuchMethod(
            Invocation.getter(#vaultsStream),
            returnValue: _i6.Stream<List<_i7.Vault>>.empty(),
          )
          as _i6.Stream<List<_i7.Vault>>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.Vault>> getAllVaults() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVaults, []),
            returnValue: _i6.Future<List<_i7.Vault>>.value(<_i7.Vault>[]),
          )
          as _i6.Future<List<_i7.Vault>>);

  @override
  _i6.Future<_i7.Vault?> getVault(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVault, [id]),
            returnValue: _i6.Future<_i7.Vault?>.value(),
          )
          as _i6.Future<_i7.Vault?>);

  @override
  _i6.Future<void> saveVault(_i7.Vault? vault) =>
      (super.noSuchMethod(
            Invocation.method(#saveVault, [vault]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addVault(_i7.Vault? vault) =>
      (super.noSuchMethod(
            Invocation.method(#addVault, [vault]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateVault(String? id, String? name, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#updateVault, [id, name, content]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteVault(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVault, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateBackupConfig(
    String? vaultId,
    ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      List<String> relays,
      String specVersion,
      _i8.BackupStatus status,
      List<
        ({
          DateTime? acknowledgedAt,
          int? acknowledgedDistributionVersion,
          String? acknowledgmentEventId,
          String? giftWrapEventId,
          String id,
          String? inviteCode,
          String? keyShare,
          DateTime? lastSeen,
          String? name,
          String? pubkey,
          _i9.StewardStatus status,
        })
      >
      stewards,
      int threshold,
      int totalKeys,
      String vaultId,
    })?
    config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBackupConfig, [vaultId, config]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<
    ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      List<String> relays,
      String specVersion,
      _i8.BackupStatus status,
      List<
        ({
          DateTime? acknowledgedAt,
          int? acknowledgedDistributionVersion,
          String? acknowledgmentEventId,
          String? giftWrapEventId,
          String id,
          String? inviteCode,
          String? keyShare,
          DateTime? lastSeen,
          String? name,
          String? pubkey,
          _i9.StewardStatus status,
        })
      >
      stewards,
      int threshold,
      int totalKeys,
      String vaultId,
    })?
  >
  getBackupConfig(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#getBackupConfig, [vaultId]),
            returnValue:
                _i6.Future<
                  ({
                    String? contentHash,
                    DateTime createdAt,
                    int distributionVersion,
                    String? instructions,
                    DateTime? lastContentChange,
                    DateTime? lastRedistribution,
                    DateTime lastUpdated,
                    List<String> relays,
                    String specVersion,
                    _i8.BackupStatus status,
                    List<
                      ({
                        DateTime? acknowledgedAt,
                        int? acknowledgedDistributionVersion,
                        String? acknowledgmentEventId,
                        String? giftWrapEventId,
                        String id,
                        String? inviteCode,
                        String? keyShare,
                        DateTime? lastSeen,
                        String? name,
                        String? pubkey,
                        _i9.StewardStatus status,
                      })
                    >
                    stewards,
                    int threshold,
                    int totalKeys,
                    String vaultId,
                  })?
                >.value(),
          )
          as _i6.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i8.BackupStatus status,
              List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i9.StewardStatus status,
                })
              >
              stewards,
              int threshold,
              int totalKeys,
              String vaultId,
            })?
          >);

  @override
  _i6.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i9.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    int? acknowledgedDistributionVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStewardStatus, [], {
              #vaultId: vaultId,
              #pubkey: pubkey,
              #status: status,
              #acknowledgedAt: acknowledgedAt,
              #acknowledgmentEventId: acknowledgmentEventId,
              #acknowledgedDistributionVersion: acknowledgedDistributionVersion,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addShardToVault(
    String? vaultId,
    ({
      int createdAt,
      String creatorPubkey,
      int? distributionVersion,
      String? instructions,
      bool? isReceived,
      String? nostrEventId,
      String? ownerName,
      List<Map<String, String>>? peers,
      String primeMod,
      DateTime? receivedAt,
      String? recipientPubkey,
      List<String>? relayUrls,
      String shard,
      int shardIndex,
      int threshold,
      int totalShards,
      String? vaultId,
      String? vaultName,
    })?
    shard,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addShardToVault, [vaultId, shard]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<
    List<
      ({
        int createdAt,
        String creatorPubkey,
        int? distributionVersion,
        String? instructions,
        bool? isReceived,
        String? nostrEventId,
        String? ownerName,
        List<Map<String, String>>? peers,
        String primeMod,
        DateTime? receivedAt,
        String? recipientPubkey,
        List<String>? relayUrls,
        String shard,
        int shardIndex,
        int threshold,
        int totalShards,
        String? vaultId,
        String? vaultName,
      })
    >
  >
  getShardsForVault(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#getShardsForVault, [vaultId]),
            returnValue:
                _i6.Future<
                  List<
                    ({
                      int createdAt,
                      String creatorPubkey,
                      int? distributionVersion,
                      String? instructions,
                      bool? isReceived,
                      String? nostrEventId,
                      String? ownerName,
                      List<Map<String, String>>? peers,
                      String primeMod,
                      DateTime? receivedAt,
                      String? recipientPubkey,
                      List<String>? relayUrls,
                      String shard,
                      int shardIndex,
                      int threshold,
                      int totalShards,
                      String? vaultId,
                      String? vaultName,
                    })
                  >
                >.value(
                  <
                    ({
                      int createdAt,
                      String creatorPubkey,
                      int? distributionVersion,
                      String? instructions,
                      bool? isReceived,
                      String? nostrEventId,
                      String? ownerName,
                      List<Map<String, String>>? peers,
                      String primeMod,
                      DateTime? receivedAt,
                      String? recipientPubkey,
                      List<String>? relayUrls,
                      String shard,
                      int shardIndex,
                      int threshold,
                      int totalShards,
                      String? vaultId,
                      String? vaultName,
                    })
                  >[],
                ),
          )
          as _i6.Future<
            List<
              ({
                int createdAt,
                String creatorPubkey,
                int? distributionVersion,
                String? instructions,
                bool? isReceived,
                String? nostrEventId,
                String? ownerName,
                List<Map<String, String>>? peers,
                String primeMod,
                DateTime? receivedAt,
                String? recipientPubkey,
                List<String>? relayUrls,
                String shard,
                int shardIndex,
                int threshold,
                int totalShards,
                String? vaultId,
                String? vaultName,
              })
            >
          >);

  @override
  _i6.Future<void> clearShardsForVault(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#clearShardsForVault, [vaultId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isKeyHolderForVault(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#isKeyHolderForVault, [vaultId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> addRecoveryRequestToVault(String? vaultId, _i10.RecoveryRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addRecoveryRequestToVault, [vaultId, request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRecoveryRequestInVault(
    String? vaultId,
    String? requestId,
    _i10.RecoveryRequest? updatedRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecoveryRequestInVault, [vaultId, requestId, updatedRequest]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.RecoveryRequest>> getRecoveryRequestsForVault(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecoveryRequestsForVault, [vaultId]),
            returnValue: _i6.Future<List<_i10.RecoveryRequest>>.value(<_i10.RecoveryRequest>[]),
          )
          as _i6.Future<List<_i10.RecoveryRequest>>);

  @override
  _i6.Future<_i10.RecoveryRequest?> getActiveRecoveryRequest(String? vaultId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRecoveryRequest, [vaultId]),
            returnValue: _i6.Future<_i10.RecoveryRequest?>.value(),
          )
          as _i6.Future<_i10.RecoveryRequest?>);

  @override
  _i6.Future<List<_i10.RecoveryRequest>> getAllRecoveryRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecoveryRequests, []),
            returnValue: _i6.Future<List<_i10.RecoveryRequest>>.value(<_i10.RecoveryRequest>[]),
          )
          as _i6.Future<List<_i10.RecoveryRequest>>);

  @override
  void dispose() =>
      super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);
}

/// A class which mocks [ShardDistributionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShardDistributionService extends _i1.Mock implements _i11.ShardDistributionService {
  MockShardDistributionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<
    List<
      ({
        String backupConfigId,
        DateTime createdAt,
        String encryptedContent,
        String eventId,
        DateTime? publishedAt,
        String recipientPubkey,
        int shardIndex,
        _i12.EventStatus status,
      })
    >
  >
  distributeShards({
    required String? ownerPubkey,
    required ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      List<String> relays,
      String specVersion,
      _i8.BackupStatus status,
      List<
        ({
          DateTime? acknowledgedAt,
          int? acknowledgedDistributionVersion,
          String? acknowledgmentEventId,
          String? giftWrapEventId,
          String id,
          String? inviteCode,
          String? keyShare,
          DateTime? lastSeen,
          String? name,
          String? pubkey,
          _i9.StewardStatus status,
        })
      >
      stewards,
      int threshold,
      int totalKeys,
      String vaultId,
    })?
    config,
    required List<
      ({
        int createdAt,
        String creatorPubkey,
        int? distributionVersion,
        String? instructions,
        bool? isReceived,
        String? nostrEventId,
        String? ownerName,
        List<Map<String, String>>? peers,
        String primeMod,
        DateTime? receivedAt,
        String? recipientPubkey,
        List<String>? relayUrls,
        String shard,
        int shardIndex,
        int threshold,
        int totalShards,
        String? vaultId,
        String? vaultName,
      })
    >?
    shards,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#distributeShards, [], {
              #ownerPubkey: ownerPubkey,
              #config: config,
              #shards: shards,
            }),
            returnValue:
                _i6.Future<
                  List<
                    ({
                      String backupConfigId,
                      DateTime createdAt,
                      String encryptedContent,
                      String eventId,
                      DateTime? publishedAt,
                      String recipientPubkey,
                      int shardIndex,
                      _i12.EventStatus status,
                    })
                  >
                >.value(
                  <
                    ({
                      String backupConfigId,
                      DateTime createdAt,
                      String encryptedContent,
                      String eventId,
                      DateTime? publishedAt,
                      String recipientPubkey,
                      int shardIndex,
                      _i12.EventStatus status,
                    })
                  >[],
                ),
          )
          as _i6.Future<
            List<
              ({
                String backupConfigId,
                DateTime createdAt,
                String encryptedContent,
                String eventId,
                DateTime? publishedAt,
                String recipientPubkey,
                int shardIndex,
                _i12.EventStatus status,
              })
            >
          >);

  @override
  _i6.Future<void> updateDistributionStatus({
    required String? vaultId,
    required List<
      ({
        String backupConfigId,
        DateTime createdAt,
        String encryptedContent,
        String eventId,
        DateTime? publishedAt,
        String recipientPubkey,
        int shardIndex,
        _i12.EventStatus status,
      })
    >?
    shardEvents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDistributionStatus, [], {
              #vaultId: vaultId,
              #shardEvents: shardEvents,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> processShardConfirmationEvent({required _i13.Nip01Event? event}) =>
      (super.noSuchMethod(
            Invocation.method(#processShardConfirmationEvent, [], {#event: event}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> processShardErrorEvent({required _i13.Nip01Event? event}) =>
      (super.noSuchMethod(
            Invocation.method(#processShardErrorEvent, [], {#event: event}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i14.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.KeyPair> generateAndStoreNostrKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateAndStoreNostrKey, []),
            returnValue: _i6.Future<_i2.KeyPair>.value(
              _FakeKeyPair_0(this, Invocation.method(#generateAndStoreNostrKey, [])),
            ),
          )
          as _i6.Future<_i2.KeyPair>);

  @override
  _i6.Future<_i2.KeyPair> importNsecKey(String? nsec) =>
      (super.noSuchMethod(
            Invocation.method(#importNsecKey, [nsec]),
            returnValue: _i6.Future<_i2.KeyPair>.value(
              _FakeKeyPair_0(this, Invocation.method(#importNsecKey, [nsec])),
            ),
          )
          as _i6.Future<_i2.KeyPair>);

  @override
  _i6.Future<_i2.KeyPair> importHexPrivateKey(String? hexPrivateKey) =>
      (super.noSuchMethod(
            Invocation.method(#importHexPrivateKey, [hexPrivateKey]),
            returnValue: _i6.Future<_i2.KeyPair>.value(
              _FakeKeyPair_0(this, Invocation.method(#importHexPrivateKey, [hexPrivateKey])),
            ),
          )
          as _i6.Future<_i2.KeyPair>);

  @override
  _i6.Future<_i2.KeyPair?> getStoredNostrKey() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredNostrKey, []),
            returnValue: _i6.Future<_i2.KeyPair?>.value(),
          )
          as _i6.Future<_i2.KeyPair?>);

  @override
  _i6.Future<_i2.KeyPair> initializeKey() =>
      (super.noSuchMethod(
            Invocation.method(#initializeKey, []),
            returnValue: _i6.Future<_i2.KeyPair>.value(
              _FakeKeyPair_0(this, Invocation.method(#initializeKey, [])),
            ),
          )
          as _i6.Future<_i2.KeyPair>);

  @override
  _i6.Future<String?> getCurrentPublicKey() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPublicKey, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getCurrentPublicKeyBech32() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPublicKeyBech32, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String> encryptText(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encryptText, [plaintext]),
            returnValue: _i6.Future<String>.value(
              _i15.dummyValue<String>(this, Invocation.method(#encryptText, [plaintext])),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> decryptText(String? encryptedText) =>
      (super.noSuchMethod(
            Invocation.method(#decryptText, [encryptedText]),
            returnValue: _i6.Future<String>.value(
              _i15.dummyValue<String>(this, Invocation.method(#decryptText, [encryptedText])),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> clearStoredKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredKeys, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void resetCacheForTest() => super.noSuchMethod(
    Invocation.method(#resetCacheForTest, []),
    returnValueForMissingStub: null,
  );

  @override
  String? npubToHex(String? npub) =>
      (super.noSuchMethod(Invocation.method(#npubToHex, [npub])) as String?);

  @override
  _i6.Future<String> encryptForRecipient({
    required String? plaintext,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encryptForRecipient, [], {
              #plaintext: plaintext,
              #recipientPubkey: recipientPubkey,
            }),
            returnValue: _i6.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#encryptForRecipient, [], {
                  #plaintext: plaintext,
                  #recipientPubkey: recipientPubkey,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> decryptFromSender({
    required String? encryptedText,
    required String? senderPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptFromSender, [], {
              #encryptedText: encryptedText,
              #senderPubkey: senderPubkey,
            }),
            returnValue: _i6.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#decryptFromSender, [], {
                  #encryptedText: encryptedText,
                  #senderPubkey: senderPubkey,
                }),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [RelayScanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayScanService extends _i1.Mock implements _i4.RelayScanService {
  MockRelayScanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NdkService get ndkService =>
      (super.noSuchMethod(
            Invocation.getter(#ndkService),
            returnValue: _FakeNdkService_1(this, Invocation.getter(#ndkService)),
          )
          as _i3.NdkService);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i16.RelayConfiguration>> getRelayConfigurations({bool? enabledOnly}) =>
      (super.noSuchMethod(
            Invocation.method(#getRelayConfigurations, [], {#enabledOnly: enabledOnly}),
            returnValue: _i6.Future<List<_i16.RelayConfiguration>>.value(
              <_i16.RelayConfiguration>[],
            ),
          )
          as _i6.Future<List<_i16.RelayConfiguration>>);

  @override
  _i6.Future<_i16.RelayConfiguration?> getRelayConfiguration(String? relayId) =>
      (super.noSuchMethod(
            Invocation.method(#getRelayConfiguration, [relayId]),
            returnValue: _i6.Future<_i16.RelayConfiguration?>.value(),
          )
          as _i6.Future<_i16.RelayConfiguration?>);

  @override
  _i6.Future<void> addRelayConfiguration(_i16.RelayConfiguration? relay) =>
      (super.noSuchMethod(
            Invocation.method(#addRelayConfiguration, [relay]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRelayConfiguration(_i16.RelayConfiguration? relay) =>
      (super.noSuchMethod(
            Invocation.method(#updateRelayConfiguration, [relay]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeRelayConfiguration(String? relayId) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelayConfiguration, [relayId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> startRelayScanning({Duration? scanInterval}) =>
      (super.noSuchMethod(
            Invocation.method(#startRelayScanning, [], {#scanInterval: scanInterval}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopRelayScanning() =>
      (super.noSuchMethod(
            Invocation.method(#stopRelayScanning, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isScanningActive() =>
      (super.noSuchMethod(
            Invocation.method(#isScanningActive, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i4.ScanningStatus> getScanningStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getScanningStatus, []),
            returnValue: _i6.Future<_i4.ScanningStatus>.value(
              _FakeScanningStatus_2(this, Invocation.method(#getScanningStatus, [])),
            ),
          )
          as _i6.Future<_i4.ScanningStatus>);

  @override
  _i6.Future<void> scanNow() =>
      (super.noSuchMethod(
            Invocation.method(#scanNow, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncRelaysFromUrls(List<String>? relayUrls) =>
      (super.noSuchMethod(
            Invocation.method(#syncRelaysFromUrls, [relayUrls]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> ensureScanningStarted() =>
      (super.noSuchMethod(
            Invocation.method(#ensureScanningStarted, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
