// Mocks generated by Mockito 5.4.4 from annotations
// in keydex/test/services/ndk_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i27;

import 'package:keydex/models/invitation_status.dart' as _i32;
import 'package:keydex/providers/lockbox_provider.dart' as _i25;
import 'package:keydex/services/invitation_sending_service.dart' as _i26;
import 'package:keydex/services/invitation_service.dart' as _i31;
import 'package:keydex/services/login_service.dart' as _i30;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i28;
import 'package:ndk/domain_layer/entities/broadcast_state.dart' as _i29;
import 'package:ndk/domain_layer/entities/nip_01_event.dart' as _i22;
import 'package:ndk/domain_layer/usecases/accounts/accounts.dart' as _i4;
import 'package:ndk/domain_layer/usecases/broadcast/broadcast.dart' as _i6;
import 'package:ndk/domain_layer/usecases/bunkers/bunkers.dart' as _i5;
import 'package:ndk/domain_layer/usecases/connectivity/connectivity.dart'
    as _i18;
import 'package:ndk/domain_layer/usecases/files/blossom.dart' as _i15;
import 'package:ndk/domain_layer/usecases/files/blossom_user_server_list.dart'
    as _i16;
import 'package:ndk/domain_layer/usecases/files/files.dart' as _i14;
import 'package:ndk/domain_layer/usecases/follows/follows.dart' as _i8;
import 'package:ndk/domain_layer/usecases/gift_wrap/gift_wrap.dart' as _i17;
import 'package:ndk/domain_layer/usecases/lists/lists.dart' as _i11;
import 'package:ndk/domain_layer/usecases/metadatas/metadatas.dart' as _i9;
import 'package:ndk/domain_layer/usecases/nip05/verify_nip_05.dart' as _i13;
import 'package:ndk/domain_layer/usecases/nwc/nwc.dart' as _i19;
import 'package:ndk/domain_layer/usecases/relay_manager.dart' as _i7;
import 'package:ndk/domain_layer/usecases/relay_sets/relay_sets.dart' as _i12;
import 'package:ndk/domain_layer/usecases/requests/requests.dart' as _i3;
import 'package:ndk/domain_layer/usecases/search/search.dart' as _i21;
import 'package:ndk/domain_layer/usecases/user_relay_lists/user_relay_lists.dart'
    as _i10;
import 'package:ndk/domain_layer/usecases/zaps/zaps.dart' as _i20;
import 'package:ndk/ndk.dart' as _i23;
import 'package:ndk/presentation_layer/ndk_config.dart' as _i2;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i24;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNdkConfig_0 extends _i1.SmartFake implements _i2.NdkConfig {
  _FakeNdkConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequests_1 extends _i1.SmartFake implements _i3.Requests {
  _FakeRequests_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccounts_2 extends _i1.SmartFake implements _i4.Accounts {
  _FakeAccounts_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBunkers_3 extends _i1.SmartFake implements _i5.Bunkers {
  _FakeBunkers_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBroadcast_4 extends _i1.SmartFake implements _i6.Broadcast {
  _FakeBroadcast_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelayManager_5<T> extends _i1.SmartFake
    implements _i7.RelayManager<T> {
  _FakeRelayManager_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFollows_6 extends _i1.SmartFake implements _i8.Follows {
  _FakeFollows_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetadatas_7 extends _i1.SmartFake implements _i9.Metadatas {
  _FakeMetadatas_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRelayLists_8 extends _i1.SmartFake
    implements _i10.UserRelayLists {
  _FakeUserRelayLists_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLists_9 extends _i1.SmartFake implements _i11.Lists {
  _FakeLists_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelaySets_10 extends _i1.SmartFake implements _i12.RelaySets {
  _FakeRelaySets_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyNip05_11 extends _i1.SmartFake implements _i13.VerifyNip05 {
  _FakeVerifyNip05_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFiles_12 extends _i1.SmartFake implements _i14.Files {
  _FakeFiles_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlossom_13 extends _i1.SmartFake implements _i15.Blossom {
  _FakeBlossom_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlossomUserServerList_14 extends _i1.SmartFake
    implements _i16.BlossomUserServerList {
  _FakeBlossomUserServerList_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGiftWrap_15 extends _i1.SmartFake implements _i17.GiftWrap {
  _FakeGiftWrap_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectivy_16 extends _i1.SmartFake implements _i18.Connectivy {
  _FakeConnectivy_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNwc_17 extends _i1.SmartFake implements _i19.Nwc {
  _FakeNwc_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZaps_18 extends _i1.SmartFake implements _i20.Zaps {
  _FakeZaps_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearch_19 extends _i1.SmartFake implements _i21.Search {
  _FakeSearch_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNip01Event_20 extends _i1.SmartFake implements _i22.Nip01Event {
  _FakeNip01Event_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdkBroadcastResponse_21 extends _i1.SmartFake
    implements _i23.NdkBroadcastResponse {
  _FakeNdkBroadcastResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyPair_22 extends _i1.SmartFake implements _i24.KeyPair {
  _FakeKeyPair_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLockboxRepository_23 extends _i1.SmartFake
    implements _i25.LockboxRepository {
  _FakeLockboxRepository_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvitationSendingService_24 extends _i1.SmartFake
    implements _i26.InvitationSendingService {
  _FakeInvitationSendingService_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_25 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ndk].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdk extends _i1.Mock implements _i23.Ndk {
  MockNdk() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NdkConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeNdkConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.NdkConfig);

  @override
  _i3.Requests get requests => (super.noSuchMethod(
        Invocation.getter(#requests),
        returnValue: _FakeRequests_1(
          this,
          Invocation.getter(#requests),
        ),
      ) as _i3.Requests);

  @override
  _i4.Accounts get accounts => (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeAccounts_2(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i4.Accounts);

  @override
  _i5.Bunkers get bunkers => (super.noSuchMethod(
        Invocation.getter(#bunkers),
        returnValue: _FakeBunkers_3(
          this,
          Invocation.getter(#bunkers),
        ),
      ) as _i5.Bunkers);

  @override
  _i6.Broadcast get broadcast => (super.noSuchMethod(
        Invocation.getter(#broadcast),
        returnValue: _FakeBroadcast_4(
          this,
          Invocation.getter(#broadcast),
        ),
      ) as _i6.Broadcast);

  @override
  _i7.RelayManager<dynamic> get relays => (super.noSuchMethod(
        Invocation.getter(#relays),
        returnValue: _FakeRelayManager_5<dynamic>(
          this,
          Invocation.getter(#relays),
        ),
      ) as _i7.RelayManager<dynamic>);

  @override
  _i8.Follows get follows => (super.noSuchMethod(
        Invocation.getter(#follows),
        returnValue: _FakeFollows_6(
          this,
          Invocation.getter(#follows),
        ),
      ) as _i8.Follows);

  @override
  _i9.Metadatas get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeMetadatas_7(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i9.Metadatas);

  @override
  _i10.UserRelayLists get userRelayLists => (super.noSuchMethod(
        Invocation.getter(#userRelayLists),
        returnValue: _FakeUserRelayLists_8(
          this,
          Invocation.getter(#userRelayLists),
        ),
      ) as _i10.UserRelayLists);

  @override
  _i11.Lists get lists => (super.noSuchMethod(
        Invocation.getter(#lists),
        returnValue: _FakeLists_9(
          this,
          Invocation.getter(#lists),
        ),
      ) as _i11.Lists);

  @override
  _i12.RelaySets get relaySets => (super.noSuchMethod(
        Invocation.getter(#relaySets),
        returnValue: _FakeRelaySets_10(
          this,
          Invocation.getter(#relaySets),
        ),
      ) as _i12.RelaySets);

  @override
  _i13.VerifyNip05 get nip05 => (super.noSuchMethod(
        Invocation.getter(#nip05),
        returnValue: _FakeVerifyNip05_11(
          this,
          Invocation.getter(#nip05),
        ),
      ) as _i13.VerifyNip05);

  @override
  _i14.Files get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFiles_12(
          this,
          Invocation.getter(#files),
        ),
      ) as _i14.Files);

  @override
  _i15.Blossom get blossom => (super.noSuchMethod(
        Invocation.getter(#blossom),
        returnValue: _FakeBlossom_13(
          this,
          Invocation.getter(#blossom),
        ),
      ) as _i15.Blossom);

  @override
  _i16.BlossomUserServerList get blossomUserServerList => (super.noSuchMethod(
        Invocation.getter(#blossomUserServerList),
        returnValue: _FakeBlossomUserServerList_14(
          this,
          Invocation.getter(#blossomUserServerList),
        ),
      ) as _i16.BlossomUserServerList);

  @override
  _i17.GiftWrap get giftWrap => (super.noSuchMethod(
        Invocation.getter(#giftWrap),
        returnValue: _FakeGiftWrap_15(
          this,
          Invocation.getter(#giftWrap),
        ),
      ) as _i17.GiftWrap);

  @override
  _i18.Connectivy get connectivity => (super.noSuchMethod(
        Invocation.getter(#connectivity),
        returnValue: _FakeConnectivy_16(
          this,
          Invocation.getter(#connectivity),
        ),
      ) as _i18.Connectivy);

  @override
  _i19.Nwc get nwc => (super.noSuchMethod(
        Invocation.getter(#nwc),
        returnValue: _FakeNwc_17(
          this,
          Invocation.getter(#nwc),
        ),
      ) as _i19.Nwc);

  @override
  _i20.Zaps get zaps => (super.noSuchMethod(
        Invocation.getter(#zaps),
        returnValue: _FakeZaps_18(
          this,
          Invocation.getter(#zaps),
        ),
      ) as _i20.Zaps);

  @override
  _i21.Search get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearch_19(
          this,
          Invocation.getter(#search),
        ),
      ) as _i21.Search);

  @override
  _i27.Future<void> destroy() => (super.noSuchMethod(
        Invocation.method(
          #destroy,
          [],
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);
}

/// A class which mocks [GiftWrap].
///
/// See the documentation for Mockito's code generation for more information.
class MockGiftWrap extends _i1.Mock implements _i17.GiftWrap {
  MockGiftWrap() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Accounts get accounts => (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _FakeAccounts_2(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i4.Accounts);

  @override
  _i27.Future<_i22.Nip01Event> toGiftWrap({
    required _i22.Nip01Event? rumor,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toGiftWrap,
          [],
          {
            #rumor: rumor,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #toGiftWrap,
            [],
            {
              #rumor: rumor,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);

  @override
  _i27.Future<_i22.Nip01Event> fromGiftWrap(
          {required _i22.Nip01Event? giftWrap}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromGiftWrap,
          [],
          {#giftWrap: giftWrap},
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #fromGiftWrap,
            [],
            {#giftWrap: giftWrap},
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);

  @override
  _i27.Future<_i22.Nip01Event> createRumor({
    String? customPubkey,
    required String? content,
    required int? kind,
    required List<List<String>>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRumor,
          [],
          {
            #customPubkey: customPubkey,
            #content: content,
            #kind: kind,
            #tags: tags,
          },
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #createRumor,
            [],
            {
              #customPubkey: customPubkey,
              #content: content,
              #kind: kind,
              #tags: tags,
            },
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);

  @override
  _i27.Future<_i22.Nip01Event> sealRumor({
    required _i22.Nip01Event? rumor,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sealRumor,
          [],
          {
            #rumor: rumor,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #sealRumor,
            [],
            {
              #rumor: rumor,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);

  @override
  _i27.Future<_i22.Nip01Event> unsealRumor(
          {required _i22.Nip01Event? sealedEvent}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsealRumor,
          [],
          {#sealedEvent: sealedEvent},
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #unsealRumor,
            [],
            {#sealedEvent: sealedEvent},
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);

  @override
  _i27.Future<_i22.Nip01Event> unwrapEvent(
          {required _i22.Nip01Event? wrappedEvent}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unwrapEvent,
          [],
          {#wrappedEvent: wrappedEvent},
        ),
        returnValue: _i27.Future<_i22.Nip01Event>.value(_FakeNip01Event_20(
          this,
          Invocation.method(
            #unwrapEvent,
            [],
            {#wrappedEvent: wrappedEvent},
          ),
        )),
      ) as _i27.Future<_i22.Nip01Event>);
}

/// A class which mocks [Broadcast].
///
/// See the documentation for Mockito's code generation for more information.
class MockBroadcast extends _i1.Mock implements _i6.Broadcast {
  MockBroadcast() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.NdkBroadcastResponse broadcast({
    required _i22.Nip01Event? nostrEvent,
    Iterable<String>? specificRelays,
    _i23.EventSigner? customSigner,
    double? considerDonePercent,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcast,
          [],
          {
            #nostrEvent: nostrEvent,
            #specificRelays: specificRelays,
            #customSigner: customSigner,
            #considerDonePercent: considerDonePercent,
            #timeout: timeout,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_21(
          this,
          Invocation.method(
            #broadcast,
            [],
            {
              #nostrEvent: nostrEvent,
              #specificRelays: specificRelays,
              #customSigner: customSigner,
              #considerDonePercent: considerDonePercent,
              #timeout: timeout,
            },
          ),
        ),
      ) as _i23.NdkBroadcastResponse);

  @override
  _i23.NdkBroadcastResponse broadcastReaction({
    required String? eventId,
    Iterable<String>? customRelays,
    String? reaction = r'+',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastReaction,
          [],
          {
            #eventId: eventId,
            #customRelays: customRelays,
            #reaction: reaction,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_21(
          this,
          Invocation.method(
            #broadcastReaction,
            [],
            {
              #eventId: eventId,
              #customRelays: customRelays,
              #reaction: reaction,
            },
          ),
        ),
      ) as _i23.NdkBroadcastResponse);

  @override
  _i23.NdkBroadcastResponse broadcastDeletion({
    required String? eventId,
    Iterable<String>? customRelays,
    _i23.EventSigner? customSigner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastDeletion,
          [],
          {
            #eventId: eventId,
            #customRelays: customRelays,
            #customSigner: customSigner,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_21(
          this,
          Invocation.method(
            #broadcastDeletion,
            [],
            {
              #eventId: eventId,
              #customRelays: customRelays,
              #customSigner: customSigner,
            },
          ),
        ),
      ) as _i23.NdkBroadcastResponse);
}

/// A class which mocks [Nip01Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockNip01Event extends _i1.Mock implements _i22.Nip01Event {
  MockNip01Event() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get pubKey => (super.noSuchMethod(
        Invocation.getter(#pubKey),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#pubKey),
        ),
      ) as String);

  @override
  int get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: 0,
      ) as int);

  @override
  set createdAt(int? _createdAt) => super.noSuchMethod(
        Invocation.setter(
          #createdAt,
          _createdAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: 0,
      ) as int);

  @override
  List<List<String>> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <List<String>>[],
      ) as List<List<String>>);

  @override
  set tags(List<List<String>>? _tags) => super.noSuchMethod(
        Invocation.setter(
          #tags,
          _tags,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#content),
        ),
      ) as String);

  @override
  set content(String? _content) => super.noSuchMethod(
        Invocation.setter(
          #content,
          _content,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get sig => (super.noSuchMethod(
        Invocation.getter(#sig),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.getter(#sig),
        ),
      ) as String);

  @override
  set sig(String? _sig) => super.noSuchMethod(
        Invocation.setter(
          #sig,
          _sig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set validSig(bool? _validSig) => super.noSuchMethod(
        Invocation.setter(
          #validSig,
          _validSig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get sources => (super.noSuchMethod(
        Invocation.getter(#sources),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set sources(List<String>? _sources) => super.noSuchMethod(
        Invocation.setter(
          #sources,
          _sources,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isIdValid => (super.noSuchMethod(
        Invocation.getter(#isIdValid),
        returnValue: false,
      ) as bool);

  @override
  List<String> get tTags => (super.noSuchMethod(
        Invocation.getter(#tTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get pTags => (super.noSuchMethod(
        Invocation.getter(#pTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get replyETags => (super.noSuchMethod(
        Invocation.getter(#replyETags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toBase64() => (super.noSuchMethod(
        Invocation.method(
          #toBase64,
          [],
        ),
        returnValue: _i28.dummyValue<String>(
          this,
          Invocation.method(
            #toBase64,
            [],
          ),
        ),
      ) as String);

  @override
  void sign(String? privateKey) => super.noSuchMethod(
        Invocation.method(
          #sign,
          [privateKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getTags(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [tag],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String? getFirstTag(String? name) => (super.noSuchMethod(Invocation.method(
        #getFirstTag,
        [name],
      )) as String?);

  @override
  _i22.Nip01Event copyWith({
    String? pubKey,
    int? createdAt,
    int? kind,
    List<List<String>>? tags,
    String? content,
    String? sig,
    List<String>? sources,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #pubKey: pubKey,
            #createdAt: createdAt,
            #kind: kind,
            #tags: tags,
            #content: content,
            #sig: sig,
            #sources: sources,
          },
        ),
        returnValue: _FakeNip01Event_20(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #pubKey: pubKey,
              #createdAt: createdAt,
              #kind: kind,
              #tags: tags,
              #content: content,
              #sig: sig,
              #sources: sources,
            },
          ),
        ),
      ) as _i22.Nip01Event);
}

/// A class which mocks [NdkBroadcastResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkBroadcastResponse extends _i1.Mock
    implements _i23.NdkBroadcastResponse {
  MockNdkBroadcastResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.Nip01Event get publishEvent => (super.noSuchMethod(
        Invocation.getter(#publishEvent),
        returnValue: _FakeNip01Event_20(
          this,
          Invocation.getter(#publishEvent),
        ),
      ) as _i22.Nip01Event);

  @override
  _i27.Future<List<_i29.RelayBroadcastResponse>> get broadcastDoneFuture =>
      (super.noSuchMethod(
        Invocation.getter(#broadcastDoneFuture),
        returnValue: _i27.Future<List<_i29.RelayBroadcastResponse>>.value(
            <_i29.RelayBroadcastResponse>[]),
      ) as _i27.Future<List<_i29.RelayBroadcastResponse>>);

  @override
  _i27.Stream<List<_i29.RelayBroadcastResponse>> get broadcastDone =>
      (super.noSuchMethod(
        Invocation.getter(#broadcastDone),
        returnValue: _i27.Stream<List<_i29.RelayBroadcastResponse>>.empty(),
      ) as _i27.Stream<List<_i29.RelayBroadcastResponse>>);
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i30.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i27.Future<_i24.KeyPair> generateAndStoreNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #generateAndStoreNostrKey,
          [],
        ),
        returnValue: _i27.Future<_i24.KeyPair>.value(_FakeKeyPair_22(
          this,
          Invocation.method(
            #generateAndStoreNostrKey,
            [],
          ),
        )),
      ) as _i27.Future<_i24.KeyPair>);

  @override
  _i27.Future<_i24.KeyPair?> getStoredNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredNostrKey,
          [],
        ),
        returnValue: _i27.Future<_i24.KeyPair?>.value(),
      ) as _i27.Future<_i24.KeyPair?>);

  @override
  _i27.Future<_i24.KeyPair> initializeKey() => (super.noSuchMethod(
        Invocation.method(
          #initializeKey,
          [],
        ),
        returnValue: _i27.Future<_i24.KeyPair>.value(_FakeKeyPair_22(
          this,
          Invocation.method(
            #initializeKey,
            [],
          ),
        )),
      ) as _i27.Future<_i24.KeyPair>);

  @override
  _i27.Future<String?> getCurrentPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKey,
          [],
        ),
        returnValue: _i27.Future<String?>.value(),
      ) as _i27.Future<String?>);

  @override
  _i27.Future<String?> getCurrentPublicKeyBech32() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKeyBech32,
          [],
        ),
        returnValue: _i27.Future<String?>.value(),
      ) as _i27.Future<String?>);

  @override
  _i27.Future<String> encryptText(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptText,
          [plaintext],
        ),
        returnValue: _i27.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #encryptText,
            [plaintext],
          ),
        )),
      ) as _i27.Future<String>);

  @override
  _i27.Future<String> decryptText(String? encryptedText) => (super.noSuchMethod(
        Invocation.method(
          #decryptText,
          [encryptedText],
        ),
        returnValue: _i27.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #decryptText,
            [encryptedText],
          ),
        )),
      ) as _i27.Future<String>);

  @override
  _i27.Future<void> clearStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearStoredKeys,
          [],
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  void resetCacheForTest() => super.noSuchMethod(
        Invocation.method(
          #resetCacheForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? npubToHex(String? npub) => (super.noSuchMethod(Invocation.method(
        #npubToHex,
        [npub],
      )) as String?);

  @override
  _i27.Future<String> encryptForRecipient({
    required String? plaintext,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptForRecipient,
          [],
          {
            #plaintext: plaintext,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i27.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #encryptForRecipient,
            [],
            {
              #plaintext: plaintext,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i27.Future<String>);

  @override
  _i27.Future<String> decryptFromSender({
    required String? encryptedText,
    required String? senderPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFromSender,
          [],
          {
            #encryptedText: encryptedText,
            #senderPubkey: senderPubkey,
          },
        ),
        returnValue: _i27.Future<String>.value(_i28.dummyValue<String>(
          this,
          Invocation.method(
            #decryptFromSender,
            [],
            {
              #encryptedText: encryptedText,
              #senderPubkey: senderPubkey,
            },
          ),
        )),
      ) as _i27.Future<String>);
}

/// A class which mocks [InvitationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationService extends _i1.Mock implements _i31.InvitationService {
  MockInvitationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.LockboxRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLockboxRepository_23(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i25.LockboxRepository);

  @override
  _i26.InvitationSendingService get invitationSendingService =>
      (super.noSuchMethod(
        Invocation.getter(#invitationSendingService),
        returnValue: _FakeInvitationSendingService_24(
          this,
          Invocation.getter(#invitationSendingService),
        ),
      ) as _i26.InvitationSendingService);

  @override
  _i27.Stream<void> get invitationsChangedStream => (super.noSuchMethod(
        Invocation.getter(#invitationsChangedStream),
        returnValue: _i27.Stream<void>.empty(),
      ) as _i27.Stream<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i27.Future<
      ({
        DateTime createdAt,
        String inviteCode,
        String? inviteeName,
        String lockboxId,
        String lockboxName,
        String ownerPubkey,
        DateTime? redeemedAt,
        String? redeemedBy,
        List<String> relayUrls,
        _i32.InvitationStatus status
      })> generateInvitationLink({
    required String? lockboxId,
    required String? inviteeName,
    required List<String>? relayUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInvitationLink,
          [],
          {
            #lockboxId: lockboxId,
            #inviteeName: inviteeName,
            #relayUrls: relayUrls,
          },
        ),
        returnValue: _i27.Future<
            ({
              DateTime createdAt,
              String inviteCode,
              String? inviteeName,
              String lockboxId,
              String lockboxName,
              String ownerPubkey,
              DateTime? redeemedAt,
              String? redeemedBy,
              List<String> relayUrls,
              _i32.InvitationStatus status
            })>.value((
          createdAt: _FakeDateTime_25(
            this,
            Invocation.method(
              #generateInvitationLink,
              [],
              {
                #lockboxId: lockboxId,
                #inviteeName: inviteeName,
                #relayUrls: relayUrls,
              },
            ),
          ),
          inviteCode: _i28.dummyValue<String>(
            this,
            Invocation.method(
              #generateInvitationLink,
              [],
              {
                #lockboxId: lockboxId,
                #inviteeName: inviteeName,
                #relayUrls: relayUrls,
              },
            ),
          ),
          inviteeName: null,
          lockboxId: _i28.dummyValue<String>(
            this,
            Invocation.method(
              #generateInvitationLink,
              [],
              {
                #lockboxId: lockboxId,
                #inviteeName: inviteeName,
                #relayUrls: relayUrls,
              },
            ),
          ),
          lockboxName: _i28.dummyValue<String>(
            this,
            Invocation.method(
              #generateInvitationLink,
              [],
              {
                #lockboxId: lockboxId,
                #inviteeName: inviteeName,
                #relayUrls: relayUrls,
              },
            ),
          ),
          ownerPubkey: _i28.dummyValue<String>(
            this,
            Invocation.method(
              #generateInvitationLink,
              [],
              {
                #lockboxId: lockboxId,
                #inviteeName: inviteeName,
                #relayUrls: relayUrls,
              },
            ),
          ),
          redeemedAt: null,
          redeemedBy: null,
          relayUrls: <String>[],
          status: _i32.InvitationStatus.created
        )),
      ) as _i27.Future<
          ({
            DateTime createdAt,
            String inviteCode,
            String? inviteeName,
            String lockboxId,
            String lockboxName,
            String ownerPubkey,
            DateTime? redeemedAt,
            String? redeemedBy,
            List<String> relayUrls,
            _i32.InvitationStatus status
          })>);

  @override
  _i27.Future<
      List<
          ({
            DateTime createdAt,
            String inviteCode,
            String? inviteeName,
            String lockboxId,
            String lockboxName,
            String ownerPubkey,
            DateTime? redeemedAt,
            String? redeemedBy,
            List<String> relayUrls,
            _i32.InvitationStatus status
          })>> getPendingInvitations(String? lockboxId) => (super.noSuchMethod(
        Invocation.method(
          #getPendingInvitations,
          [lockboxId],
        ),
        returnValue: _i27.Future<
            List<
                ({
                  DateTime createdAt,
                  String inviteCode,
                  String? inviteeName,
                  String lockboxId,
                  String lockboxName,
                  String ownerPubkey,
                  DateTime? redeemedAt,
                  String? redeemedBy,
                  List<String> relayUrls,
                  _i32.InvitationStatus status
                })>>.value(<({
          DateTime createdAt,
          String inviteCode,
          String? inviteeName,
          String lockboxId,
          String lockboxName,
          String ownerPubkey,
          DateTime? redeemedAt,
          String? redeemedBy,
          List<String> relayUrls,
          _i32.InvitationStatus status
        })>[]),
      ) as _i27.Future<
          List<
              ({
                DateTime createdAt,
                String inviteCode,
                String? inviteeName,
                String lockboxId,
                String lockboxName,
                String ownerPubkey,
                DateTime? redeemedAt,
                String? redeemedBy,
                List<String> relayUrls,
                _i32.InvitationStatus status
              })>>);

  @override
  _i27.Future<
      ({
        DateTime createdAt,
        String inviteCode,
        String? inviteeName,
        String lockboxId,
        String lockboxName,
        String ownerPubkey,
        DateTime? redeemedAt,
        String? redeemedBy,
        List<String> relayUrls,
        _i32.InvitationStatus status
      })?> lookupInvitationByCode(String? inviteCode) => (super.noSuchMethod(
        Invocation.method(
          #lookupInvitationByCode,
          [inviteCode],
        ),
        returnValue: _i27.Future<
            ({
              DateTime createdAt,
              String inviteCode,
              String? inviteeName,
              String lockboxId,
              String lockboxName,
              String ownerPubkey,
              DateTime? redeemedAt,
              String? redeemedBy,
              List<String> relayUrls,
              _i32.InvitationStatus status
            })?>.value(),
      ) as _i27.Future<
          ({
            DateTime createdAt,
            String inviteCode,
            String? inviteeName,
            String lockboxId,
            String lockboxName,
            String ownerPubkey,
            DateTime? redeemedAt,
            String? redeemedBy,
            List<String> relayUrls,
            _i32.InvitationStatus status
          })?>);

  @override
  _i27.Future<void> createReceivedInvitation({
    required String? inviteCode,
    required String? lockboxId,
    required String? ownerPubkey,
    required List<String>? relayUrls,
    String? lockboxName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReceivedInvitation,
          [],
          {
            #inviteCode: inviteCode,
            #lockboxId: lockboxId,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
            #lockboxName: lockboxName,
          },
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  _i27.Future<void> redeemInvitation({
    required String? inviteCode,
    required String? inviteePubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redeemInvitation,
          [],
          {
            #inviteCode: inviteCode,
            #inviteePubkey: inviteePubkey,
          },
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  _i27.Future<void> denyInvitation({
    required String? inviteCode,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #denyInvitation,
          [],
          {
            #inviteCode: inviteCode,
            #reason: reason,
          },
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  _i27.Future<void> invalidateInvitation({
    required String? inviteCode,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateInvitation,
          [],
          {
            #inviteCode: inviteCode,
            #reason: reason,
          },
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  _i27.Future<void> processRsvpEvent({required _i22.Nip01Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRsvpEvent,
          [],
          {#event: event},
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);

  @override
  _i27.Future<void> processDenialEvent({required _i22.Nip01Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processDenialEvent,
          [],
          {#event: event},
        ),
        returnValue: _i27.Future<void>.value(),
        returnValueForMissingStub: _i27.Future<void>.value(),
      ) as _i27.Future<void>);
}
