// Mocks generated by Mockito 5.4.4 from annotations
// in horcrux/test/services/recovery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:horcrux/models/backup_status.dart' as _i7;
import 'package:horcrux/models/event_status.dart' as _i10;
import 'package:horcrux/models/steward_status.dart' as _i6;
import 'package:horcrux/models/recovery_request.dart' as _i12;
import 'package:horcrux/providers/vault_provider.dart' as _i3;
import 'package:horcrux/services/backup_service.dart' as _i4;
import 'package:horcrux/services/vault_share_service.dart' as _i13;
import 'package:horcrux/services/ndk_service.dart' as _i11;
import 'package:horcrux/services/shard_distribution_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:ndk/ndk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeNdk_1 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVaultRepository_2 extends _i1.SmartFake implements _i3.VaultRepository {
  _FakeVaultRepository_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i4.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })> keyHolders,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        String vaultId,
        List<String> relays,
        String specVersion,
        _i7.BackupStatus status,
        int threshold,
        int totalKeys,
      })> createBackupConfiguration({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })>?
        keyHolders,
    required List<String>? relays,
    String? instructions,
    String? contentHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#createBackupConfiguration, [], {
          #vaultId: vaultId,
          #threshold: threshold,
          #totalKeys: totalKeys,
          #keyHolders: keyHolders,
          #relays: relays,
          #instructions: instructions,
          #contentHash: contentHash,
        }),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              List<
                  ({
                    DateTime? acknowledgedAt,
                    int? acknowledgedDistributionVersion,
                    String? acknowledgmentEventId,
                    String? giftWrapEventId,
                    String id,
                    String? inviteCode,
                    String? keyShare,
                    DateTime? lastSeen,
                    String? name,
                    String? pubkey,
                    _i6.KeyHolderStatus status,
                  })> keyHolders,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              String vaultId,
              List<String> relays,
              String specVersion,
              _i7.BackupStatus status,
              int threshold,
              int totalKeys,
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(#createBackupConfiguration, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
              #contentHash: contentHash,
            }),
          ),
          distributionVersion: 0,
          instructions: null,
          keyHolders: <({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })>[],
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(#createBackupConfiguration, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
              #contentHash: contentHash,
            }),
          ),
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(#createBackupConfiguration, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
              #contentHash: contentHash,
            }),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(#createBackupConfiguration, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
              #contentHash: contentHash,
            }),
          ),
          status: _i7.BackupStatus.pending,
          threshold: 0,
          totalKeys: 0,
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })> keyHolders,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        String vaultId,
        List<String> relays,
        String specVersion,
        _i7.BackupStatus status,
        int threshold,
        int totalKeys,
      })?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#getBackupConfig, [vaultId]),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              List<
                  ({
                    DateTime? acknowledgedAt,
                    int? acknowledgedDistributionVersion,
                    String? acknowledgmentEventId,
                    String? giftWrapEventId,
                    String id,
                    String? inviteCode,
                    String? keyShare,
                    DateTime? lastSeen,
                    String? name,
                    String? pubkey,
                    _i6.KeyHolderStatus status,
                  })> keyHolders,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              String vaultId,
              List<String> relays,
              String specVersion,
              _i7.BackupStatus status,
              int threshold,
              int totalKeys,
            })?>.value(),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })?>);

  @override
  _i5.Future<
      List<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>> getAllBackupConfigs() => (super.noSuchMethod(
        Invocation.method(#getAllBackupConfigs, []),
        returnValue: _i5.Future<
            List<
                ({
                  String? contentHash,
                  DateTime createdAt,
                  int distributionVersion,
                  String? instructions,
                  List<
                      ({
                        DateTime? acknowledgedAt,
                        int? acknowledgedDistributionVersion,
                        String? acknowledgmentEventId,
                        String? giftWrapEventId,
                        String id,
                        String? inviteCode,
                        String? keyShare,
                        DateTime? lastSeen,
                        String? name,
                        String? pubkey,
                        _i6.KeyHolderStatus status,
                      })> keyHolders,
                  DateTime? lastContentChange,
                  DateTime? lastRedistribution,
                  DateTime lastUpdated,
                  String vaultId,
                  List<String> relays,
                  String specVersion,
                  _i7.BackupStatus status,
                  int threshold,
                  int totalKeys,
                })>>.value(
          <({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                String? contentHash,
                DateTime createdAt,
                int distributionVersion,
                String? instructions,
                List<
                    ({
                      DateTime? acknowledgedAt,
                      int? acknowledgedDistributionVersion,
                      String? acknowledgmentEventId,
                      String? giftWrapEventId,
                      String id,
                      String? inviteCode,
                      String? keyShare,
                      DateTime? lastSeen,
                      String? name,
                      String? pubkey,
                      _i6.KeyHolderStatus status,
                    })> keyHolders,
                DateTime? lastContentChange,
                DateTime? lastRedistribution,
                DateTime lastUpdated,
                String vaultId,
                List<String> relays,
                String specVersion,
                _i7.BackupStatus status,
                int threshold,
                int totalKeys,
              })>>);

  @override
  _i5.Future<void> updateBackupConfig(
    ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      List<
          ({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })> keyHolders,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      String vaultId,
      List<String> relays,
      String specVersion,
      _i7.BackupStatus status,
      int threshold,
      int totalKeys,
    })? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateBackupConfig, [config]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#deleteBackupConfig, [vaultId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<
      List<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>> generateShamirShares({
    required String? content,
    required int? threshold,
    required int? totalShards,
    required String? creatorPubkey,
    required String? vaultId,
    required String? vaultName,
    required List<Map<String, String>>? peers,
    String? ownerName,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#generateShamirShares, [], {
          #content: content,
          #threshold: threshold,
          #totalShards: totalShards,
          #creatorPubkey: creatorPubkey,
          #vaultId: vaultId,
          #vaultName: vaultName,
          #peers: peers,
          #ownerName: ownerName,
          #instructions: instructions,
        }),
        returnValue: _i5.Future<
            List<
                ({
                  int createdAt,
                  String creatorPubkey,
                  int? distributionVersion,
                  String? instructions,
                  bool? isReceived,
                  String? vaultId,
                  String? vaultName,
                  String? nostrEventId,
                  String? ownerName,
                  List<Map<String, String>>? peers,
                  String primeMod,
                  DateTime? receivedAt,
                  String? recipientPubkey,
                  List<String>? relayUrls,
                  String shard,
                  int shardIndex,
                  int threshold,
                  int totalShards,
                })>>.value(
          <({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                int createdAt,
                String creatorPubkey,
                int? distributionVersion,
                String? instructions,
                bool? isReceived,
                String? vaultId,
                String? vaultName,
                String? nostrEventId,
                String? ownerName,
                List<Map<String, String>>? peers,
                String primeMod,
                DateTime? receivedAt,
                String? recipientPubkey,
                List<String>? relayUrls,
                String shard,
                int shardIndex,
                int threshold,
                int totalShards,
              })>>);

  @override
  _i5.Future<String> reconstructFromShares({
    required List<
            ({
              int createdAt,
              String creatorPubkey,
              int? distributionVersion,
              String? instructions,
              bool? isReceived,
              String? vaultId,
              String? vaultName,
              String? nostrEventId,
              String? ownerName,
              List<Map<String, String>>? peers,
              String primeMod,
              DateTime? receivedAt,
              String? recipientPubkey,
              List<String>? relayUrls,
              String shard,
              int shardIndex,
              int threshold,
              int totalShards,
            })>?
        shares,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#reconstructFromShares, [], {#shares: shares}),
        returnValue: _i5.Future<String>.value(
          _i8.dummyValue<String>(
            this,
            Invocation.method(#reconstructFromShares, [], {
              #shares: shares,
            }),
          ),
        ),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateBackupStatus(
    String? vaultId,
    _i7.BackupStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateBackupStatus, [vaultId, status]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateKeyHolderStatus({
    required String? vaultId,
    required String? pubkey,
    required _i6.KeyHolderStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#updateKeyHolderStatus, [], {
          #vaultId: vaultId,
          #pubkey: pubkey,
          #status: status,
          #acknowledgedAt: acknowledgedAt,
          #acknowledgmentEventId: acknowledgmentEventId,
        }),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isBackupReady(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#isBackupReady, [vaultId]),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })> keyHolders,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        String vaultId,
        List<String> relays,
        String specVersion,
        _i7.BackupStatus status,
        int threshold,
        int totalKeys,
      })> mergeBackupConfig({
    required String? vaultId,
    int? threshold,
    List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })>?
        keyHolders,
    List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#mergeBackupConfig, [], {
          #vaultId: vaultId,
          #threshold: threshold,
          #keyHolders: keyHolders,
          #relays: relays,
          #instructions: instructions,
        }),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              List<
                  ({
                    DateTime? acknowledgedAt,
                    int? acknowledgedDistributionVersion,
                    String? acknowledgmentEventId,
                    String? giftWrapEventId,
                    String id,
                    String? inviteCode,
                    String? keyShare,
                    DateTime? lastSeen,
                    String? name,
                    String? pubkey,
                    _i6.KeyHolderStatus status,
                  })> keyHolders,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              String vaultId,
              List<String> relays,
              String specVersion,
              _i7.BackupStatus status,
              int threshold,
              int totalKeys,
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(#mergeBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          distributionVersion: 0,
          instructions: null,
          keyHolders: <({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })>[],
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(#mergeBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(#mergeBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(#mergeBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          status: _i7.BackupStatus.pending,
          threshold: 0,
          totalKeys: 0,
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })> keyHolders,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        String vaultId,
        List<String> relays,
        String specVersion,
        _i7.BackupStatus status,
        int threshold,
        int totalKeys,
      })> saveBackupConfig({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })>?
        keyHolders,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#saveBackupConfig, [], {
          #vaultId: vaultId,
          #threshold: threshold,
          #totalKeys: totalKeys,
          #keyHolders: keyHolders,
          #relays: relays,
          #instructions: instructions,
        }),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              List<
                  ({
                    DateTime? acknowledgedAt,
                    int? acknowledgedDistributionVersion,
                    String? acknowledgmentEventId,
                    String? giftWrapEventId,
                    String id,
                    String? inviteCode,
                    String? keyShare,
                    DateTime? lastSeen,
                    String? name,
                    String? pubkey,
                    _i6.KeyHolderStatus status,
                  })> keyHolders,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              String vaultId,
              List<String> relays,
              String specVersion,
              _i7.BackupStatus status,
              int threshold,
              int totalKeys,
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(#saveBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          distributionVersion: 0,
          instructions: null,
          keyHolders: <({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })>[],
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(#saveBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(#saveBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(#saveBackupConfig, [], {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #keyHolders: keyHolders,
              #relays: relays,
              #instructions: instructions,
            }),
          ),
          status: _i7.BackupStatus.pending,
          threshold: 0,
          totalKeys: 0,
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        List<
            ({
              DateTime? acknowledgedAt,
              int? acknowledgedDistributionVersion,
              String? acknowledgmentEventId,
              String? giftWrapEventId,
              String id,
              String? inviteCode,
              String? keyShare,
              DateTime? lastSeen,
              String? name,
              String? pubkey,
              _i6.KeyHolderStatus status,
            })> keyHolders,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        String vaultId,
        List<String> relays,
        String specVersion,
        _i7.BackupStatus status,
        int threshold,
        int totalKeys,
      })> createAndDistributeBackup({required String? vaultId}) => (super.noSuchMethod(
        Invocation.method(#createAndDistributeBackup, [], {
          #vaultId: vaultId,
        }),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              List<
                  ({
                    DateTime? acknowledgedAt,
                    int? acknowledgedDistributionVersion,
                    String? acknowledgmentEventId,
                    String? giftWrapEventId,
                    String id,
                    String? inviteCode,
                    String? keyShare,
                    DateTime? lastSeen,
                    String? name,
                    String? pubkey,
                    _i6.KeyHolderStatus status,
                  })> keyHolders,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              String vaultId,
              List<String> relays,
              String specVersion,
              _i7.BackupStatus status,
              int threshold,
              int totalKeys,
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(#createAndDistributeBackup, [], {
              #vaultId: vaultId,
            }),
          ),
          distributionVersion: 0,
          instructions: null,
          keyHolders: <({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })>[],
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(#createAndDistributeBackup, [], {
              #vaultId: vaultId,
            }),
          ),
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(#createAndDistributeBackup, [], {
              #vaultId: vaultId,
            }),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(#createAndDistributeBackup, [], {
              #vaultId: vaultId,
            }),
          ),
          status: _i7.BackupStatus.pending,
          threshold: 0,
          totalKeys: 0,
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            List<
                ({
                  DateTime? acknowledgedAt,
                  int? acknowledgedDistributionVersion,
                  String? acknowledgmentEventId,
                  String? giftWrapEventId,
                  String id,
                  String? inviteCode,
                  String? keyShare,
                  DateTime? lastSeen,
                  String? name,
                  String? pubkey,
                  _i6.KeyHolderStatus status,
                })> keyHolders,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            String vaultId,
            List<String> relays,
            String specVersion,
            _i7.BackupStatus status,
            int threshold,
            int totalKeys,
          })>);
}

/// A class which mocks [ShardDistributionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShardDistributionService extends _i1.Mock implements _i9.ShardDistributionService {
  MockShardDistributionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      List<
          ({
            String backupConfigId,
            DateTime createdAt,
            String encryptedContent,
            String eventId,
            DateTime? publishedAt,
            String recipientPubkey,
            int shardIndex,
            _i10.EventStatus status,
          })>> distributeShards({
    required String? ownerPubkey,
    required ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      List<
          ({
            DateTime? acknowledgedAt,
            int? acknowledgedDistributionVersion,
            String? acknowledgmentEventId,
            String? giftWrapEventId,
            String id,
            String? inviteCode,
            String? keyShare,
            DateTime? lastSeen,
            String? name,
            String? pubkey,
            _i6.KeyHolderStatus status,
          })> keyHolders,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      String vaultId,
      List<String> relays,
      String specVersion,
      _i7.BackupStatus status,
      int threshold,
      int totalKeys,
    })? config,
    required List<
            ({
              int createdAt,
              String creatorPubkey,
              int? distributionVersion,
              String? instructions,
              bool? isReceived,
              String? vaultId,
              String? vaultName,
              String? nostrEventId,
              String? ownerName,
              List<Map<String, String>>? peers,
              String primeMod,
              DateTime? receivedAt,
              String? recipientPubkey,
              List<String>? relayUrls,
              String shard,
              int shardIndex,
              int threshold,
              int totalShards,
            })>?
        shards,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#distributeShards, [], {
          #ownerPubkey: ownerPubkey,
          #config: config,
          #shards: shards,
        }),
        returnValue: _i5.Future<
            List<
                ({
                  String backupConfigId,
                  DateTime createdAt,
                  String encryptedContent,
                  String eventId,
                  DateTime? publishedAt,
                  String recipientPubkey,
                  int shardIndex,
                  _i10.EventStatus status,
                })>>.value(
          <({
            String backupConfigId,
            DateTime createdAt,
            String encryptedContent,
            String eventId,
            DateTime? publishedAt,
            String recipientPubkey,
            int shardIndex,
            _i10.EventStatus status,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                String backupConfigId,
                DateTime createdAt,
                String encryptedContent,
                String eventId,
                DateTime? publishedAt,
                String recipientPubkey,
                int shardIndex,
                _i10.EventStatus status,
              })>>);

  @override
  _i5.Future<void> updateDistributionStatus({
    required String? vaultId,
    required List<
            ({
              String backupConfigId,
              DateTime createdAt,
              String encryptedContent,
              String eventId,
              DateTime? publishedAt,
              String recipientPubkey,
              int shardIndex,
              _i10.EventStatus status,
            })>?
        shardEvents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#updateDistributionStatus, [], {
          #vaultId: vaultId,
          #shardEvents: shardEvents,
        }),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processShardConfirmationEvent({
    required _i2.Nip01Event? event,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#processShardConfirmationEvent, [], {
          #event: event,
        }),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processShardErrorEvent({required _i2.Nip01Event? event}) => (super.noSuchMethod(
        Invocation.method(#processShardErrorEvent, [], {#event: event}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i11.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i12.RecoveryRequest> get recoveryRequestStream => (super.noSuchMethod(
        Invocation.getter(#recoveryRequestStream),
        returnValue: _i5.Stream<_i12.RecoveryRequest>.empty(),
      ) as _i5.Stream<_i12.RecoveryRequest>);

  @override
  _i5.Stream<_i11.RecoveryResponseEvent> get recoveryResponseStream => (super.noSuchMethod(
        Invocation.getter(#recoveryResponseStream),
        returnValue: _i5.Stream<_i11.RecoveryResponseEvent>.empty(),
      ) as _i5.Stream<_i11.RecoveryResponseEvent>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(#initialize, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(#addRelay, [relayUrl]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(#removeRelay, [relayUrl]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> publishRecoveryRequest({
    required String? vaultId,
    required List<String>? stewardPubkeys,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#publishRecoveryRequest, [], {
          #vaultId: vaultId,
          #stewardPubkeys: stewardPubkeys,
          #expiresAt: expiresAt,
        }),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishRecoveryResponse({
    required String? initiatorPubkey,
    required String? recoveryRequestId,
    required bool? approved,
    String? shardDataJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#publishRecoveryResponse, [], {
          #initiatorPubkey: initiatorPubkey,
          #recoveryRequestId: recoveryRequestId,
          #approved: approved,
          #shardDataJson: shardDataJson,
        }),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(#stopListening, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(#getActiveRelays, []),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(#getCurrentPubkey, []),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#publishEncryptedEvent, [], {
          #content: content,
          #kind: kind,
          #recipientPubkey: recipientPubkey,
          #relays: relays,
          #tags: tags,
          #customPubkey: customPubkey,
        }),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<List<String>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#publishEncryptedEventToMultiple, [], {
          #content: content,
          #kind: kind,
          #recipientPubkeys: recipientPubkeys,
          #relays: relays,
          #tags: tags,
          #customPubkey: customPubkey,
        }),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<_i2.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(#getNdk, []),
        returnValue: _i5.Future<_i2.Ndk>.value(
          _FakeNdk_1(this, Invocation.method(#getNdk, [])),
        ),
      ) as _i5.Future<_i2.Ndk>);

  @override
  void setNdkForTesting(_i2.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(#setNdkForTesting, [ndk]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [VaultShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultShareService extends _i1.Mock implements _i13.VaultShareService {
  MockVaultShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VaultRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeVaultRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.VaultRepository);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(#initialize, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<
      List<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>> getVaultShares(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#getVaultShares, [vaultId]),
        returnValue: _i5.Future<
            List<
                ({
                  int createdAt,
                  String creatorPubkey,
                  int? distributionVersion,
                  String? instructions,
                  bool? isReceived,
                  String? vaultId,
                  String? vaultName,
                  String? nostrEventId,
                  String? ownerName,
                  List<Map<String, String>>? peers,
                  String primeMod,
                  DateTime? receivedAt,
                  String? recipientPubkey,
                  List<String>? relayUrls,
                  String shard,
                  int shardIndex,
                  int threshold,
                  int totalShards,
                })>>.value(
          <({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                int createdAt,
                String creatorPubkey,
                int? distributionVersion,
                String? instructions,
                bool? isReceived,
                String? vaultId,
                String? vaultName,
                String? nostrEventId,
                String? ownerName,
                List<Map<String, String>>? peers,
                String primeMod,
                DateTime? receivedAt,
                String? recipientPubkey,
                List<String>? relayUrls,
                String shard,
                int shardIndex,
                int threshold,
                int totalShards,
              })>>);

  @override
  _i5.Future<
      ({
        int createdAt,
        String creatorPubkey,
        int? distributionVersion,
        String? instructions,
        bool? isReceived,
        String? vaultId,
        String? vaultName,
        String? nostrEventId,
        String? ownerName,
        List<Map<String, String>>? peers,
        String primeMod,
        DateTime? receivedAt,
        String? recipientPubkey,
        List<String>? relayUrls,
        String shard,
        int shardIndex,
        int threshold,
        int totalShards,
      })?> getVaultShare(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#getVaultShare, [vaultId]),
        returnValue: _i5.Future<
            ({
              int createdAt,
              String creatorPubkey,
              int? distributionVersion,
              String? instructions,
              bool? isReceived,
              String? vaultId,
              String? vaultName,
              String? nostrEventId,
              String? ownerName,
              List<Map<String, String>>? peers,
              String primeMod,
              DateTime? receivedAt,
              String? recipientPubkey,
              List<String>? relayUrls,
              String shard,
              int shardIndex,
              int threshold,
              int totalShards,
            })?>.value(),
      ) as _i5.Future<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })?>);

  @override
  _i5.Future<
      ({
        int createdAt,
        String creatorPubkey,
        int? distributionVersion,
        String? instructions,
        bool? isReceived,
        String? vaultId,
        String? vaultName,
        String? nostrEventId,
        String? ownerName,
        List<Map<String, String>>? peers,
        String primeMod,
        DateTime? receivedAt,
        String? recipientPubkey,
        List<String>? relayUrls,
        String shard,
        int shardIndex,
        int threshold,
        int totalShards,
      })?> getShareByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(#getShareByEventId, [nostrEventId]),
        returnValue: _i5.Future<
            ({
              int createdAt,
              String creatorPubkey,
              int? distributionVersion,
              String? instructions,
              bool? isReceived,
              String? vaultId,
              String? vaultName,
              String? nostrEventId,
              String? ownerName,
              List<Map<String, String>>? peers,
              String primeMod,
              DateTime? receivedAt,
              String? recipientPubkey,
              List<String>? relayUrls,
              String shard,
              int shardIndex,
              int threshold,
              int totalShards,
            })?>.value(),
      ) as _i5.Future<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })?>);

  @override
  _i5.Future<void> addVaultShare(
    String? vaultId,
    ({
      int createdAt,
      String creatorPubkey,
      int? distributionVersion,
      String? instructions,
      bool? isReceived,
      String? vaultId,
      String? vaultName,
      String? nostrEventId,
      String? ownerName,
      List<Map<String, String>>? peers,
      String primeMod,
      DateTime? receivedAt,
      String? recipientPubkey,
      List<String>? relayUrls,
      String shard,
      int shardIndex,
      int threshold,
      int totalShards,
    })? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#addVaultShare, [vaultId, shardData]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processVaultShare(
    String? vaultId,
    ({
      int createdAt,
      String creatorPubkey,
      int? distributionVersion,
      String? instructions,
      bool? isReceived,
      String? vaultId,
      String? vaultName,
      String? nostrEventId,
      String? ownerName,
      List<Map<String, String>>? peers,
      String primeMod,
      DateTime? receivedAt,
      String? recipientPubkey,
      List<String>? relayUrls,
      String shard,
      int shardIndex,
      int threshold,
      int totalShards,
    })? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#processVaultShare, [vaultId, shardData]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> sendShardConfirmationEvent({
    required String? vaultId,
    required int? shardIndex,
    required String? ownerPubkey,
    required List<String>? relayUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#sendShardConfirmationEvent, [], {
          #vaultId: vaultId,
          #shardIndex: shardIndex,
          #ownerPubkey: ownerPubkey,
          #relayUrls: relayUrls,
        }),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> markShareAsReceived(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#markShareAsReceived, [vaultId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markShareAsReceivedByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(#markShareAsReceivedByEventId, [nostrEventId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> reassembleVaultContent(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#reassembleVaultContent, [vaultId]),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasShard(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#hasShard, [vaultId]),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<
      List<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>> getAllCollectedShards() => (super.noSuchMethod(
        Invocation.method(#getAllCollectedShards, []),
        returnValue: _i5.Future<
            List<
                ({
                  int createdAt,
                  String creatorPubkey,
                  int? distributionVersion,
                  String? instructions,
                  bool? isReceived,
                  String? vaultId,
                  String? vaultName,
                  String? nostrEventId,
                  String? ownerName,
                  List<Map<String, String>>? peers,
                  String primeMod,
                  DateTime? receivedAt,
                  String? recipientPubkey,
                  List<String>? relayUrls,
                  String shard,
                  int shardIndex,
                  int threshold,
                  int totalShards,
                })>>.value(
          <({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                int createdAt,
                String creatorPubkey,
                int? distributionVersion,
                String? instructions,
                bool? isReceived,
                String? vaultId,
                String? vaultName,
                String? nostrEventId,
                String? ownerName,
                List<Map<String, String>>? peers,
                String primeMod,
                DateTime? receivedAt,
                String? recipientPubkey,
                List<String>? relayUrls,
                String shard,
                int shardIndex,
                int threshold,
                int totalShards,
              })>>);

  @override
  _i5.Future<List<String>> getVaultesWithShares() => (super.noSuchMethod(
        Invocation.method(#getVaultesWithShares, []),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> isKeyHolderForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#isKeyHolderForVault, [vaultId]),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getShardCount(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#getShardCount, [vaultId]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> removeVaultShare(String? vaultId) => (super.noSuchMethod(
        Invocation.method(#removeVaultShare, [vaultId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeShareByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(#removeShareByEventId, [nostrEventId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTotalShardCount() => (super.noSuchMethod(
        Invocation.method(#getTotalShardCount, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> addRecoveryShard(
    String? recoveryRequestId,
    ({
      int createdAt,
      String creatorPubkey,
      int? distributionVersion,
      String? instructions,
      bool? isReceived,
      String? vaultId,
      String? vaultName,
      String? nostrEventId,
      String? ownerName,
      List<Map<String, String>>? peers,
      String primeMod,
      DateTime? receivedAt,
      String? recipientPubkey,
      List<String>? relayUrls,
      String shard,
      int shardIndex,
      int threshold,
      int totalShards,
    })? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#addRecoveryShard, [
          recoveryRequestId,
          shardData,
        ]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<
      List<
          ({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>> getRecoveryShards(String? recoveryRequestId) => (super.noSuchMethod(
        Invocation.method(#getRecoveryShards, [recoveryRequestId]),
        returnValue: _i5.Future<
            List<
                ({
                  int createdAt,
                  String creatorPubkey,
                  int? distributionVersion,
                  String? instructions,
                  bool? isReceived,
                  String? vaultId,
                  String? vaultName,
                  String? nostrEventId,
                  String? ownerName,
                  List<Map<String, String>>? peers,
                  String primeMod,
                  DateTime? receivedAt,
                  String? recipientPubkey,
                  List<String>? relayUrls,
                  String shard,
                  int shardIndex,
                  int threshold,
                  int totalShards,
                })>>.value(
          <({
            int createdAt,
            String creatorPubkey,
            int? distributionVersion,
            String? instructions,
            bool? isReceived,
            String? vaultId,
            String? vaultName,
            String? nostrEventId,
            String? ownerName,
            List<Map<String, String>>? peers,
            String primeMod,
            DateTime? receivedAt,
            String? recipientPubkey,
            List<String>? relayUrls,
            String shard,
            int shardIndex,
            int threshold,
            int totalShards,
          })>[],
        ),
      ) as _i5.Future<
          List<
              ({
                int createdAt,
                String creatorPubkey,
                int? distributionVersion,
                String? instructions,
                bool? isReceived,
                String? vaultId,
                String? vaultName,
                String? nostrEventId,
                String? ownerName,
                List<Map<String, String>>? peers,
                String primeMod,
                DateTime? receivedAt,
                String? recipientPubkey,
                List<String>? relayUrls,
                String shard,
                int shardIndex,
                int threshold,
                int totalShards,
              })>>);

  @override
  _i5.Future<int> getRecoveryShardCount(String? recoveryRequestId) => (super.noSuchMethod(
        Invocation.method(#getRecoveryShardCount, [recoveryRequestId]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> hasSufficientRecoveryShards(
    String? recoveryRequestId,
    int? threshold,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#hasSufficientRecoveryShards, [
          recoveryRequestId,
          threshold,
        ]),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> removeRecoveryShards(String? recoveryRequestId) => (super.noSuchMethod(
        Invocation.method(#removeRecoveryShards, [recoveryRequestId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(#clearAll, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(#refresh, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
