// Mocks generated by Mockito 5.4.4 from annotations
// in keydex/test/services/shard_distribution_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:ndk/domain_layer/entities/broadcast_state.dart' as _i5;
import 'package:ndk/ndk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNdkBroadcastResponse_0 extends _i1.SmartFake implements _i2.NdkBroadcastResponse {
  _FakeNdkBroadcastResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdkResponse_1 extends _i1.SmartFake implements _i2.NdkResponse {
  _FakeNdkResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNip01Event_2 extends _i1.SmartFake implements _i2.Nip01Event {
  _FakeNip01Event_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Broadcast].
///
/// See the documentation for Mockito's code generation for more information.
class MockBroadcast extends _i1.Mock implements _i2.Broadcast {
  MockBroadcast() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NdkBroadcastResponse broadcast({
    required _i2.Nip01Event? nostrEvent,
    Iterable<String>? specificRelays,
    _i2.EventSigner? customSigner,
    double? considerDonePercent,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcast,
          [],
          {
            #nostrEvent: nostrEvent,
            #specificRelays: specificRelays,
            #customSigner: customSigner,
            #considerDonePercent: considerDonePercent,
            #timeout: timeout,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_0(
          this,
          Invocation.method(
            #broadcast,
            [],
            {
              #nostrEvent: nostrEvent,
              #specificRelays: specificRelays,
              #customSigner: customSigner,
              #considerDonePercent: considerDonePercent,
              #timeout: timeout,
            },
          ),
        ),
      ) as _i2.NdkBroadcastResponse);

  @override
  _i2.NdkBroadcastResponse broadcastReaction({
    required String? eventId,
    Iterable<String>? customRelays,
    String? reaction = r'+',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastReaction,
          [],
          {
            #eventId: eventId,
            #customRelays: customRelays,
            #reaction: reaction,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_0(
          this,
          Invocation.method(
            #broadcastReaction,
            [],
            {
              #eventId: eventId,
              #customRelays: customRelays,
              #reaction: reaction,
            },
          ),
        ),
      ) as _i2.NdkBroadcastResponse);

  @override
  _i2.NdkBroadcastResponse broadcastDeletion({
    required String? eventId,
    Iterable<String>? customRelays,
    _i2.EventSigner? customSigner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastDeletion,
          [],
          {
            #eventId: eventId,
            #customRelays: customRelays,
            #customSigner: customSigner,
          },
        ),
        returnValue: _FakeNdkBroadcastResponse_0(
          this,
          Invocation.method(
            #broadcastDeletion,
            [],
            {
              #eventId: eventId,
              #customRelays: customRelays,
              #customSigner: customSigner,
            },
          ),
        ),
      ) as _i2.NdkBroadcastResponse);
}

/// A class which mocks [Requests].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequests extends _i1.Mock implements _i2.Requests {
  MockRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NdkResponse query({
    required List<_i2.Filter>? filters,
    String? name = r'',
    _i2.RelaySet? relaySet,
    bool? cacheRead = true,
    bool? cacheWrite = true,
    Duration? timeout,
    dynamic Function()? timeoutCallbackUserFacing,
    dynamic Function()? timeoutCallback,
    Iterable<String>? explicitRelays,
    int? desiredCoverage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [],
          {
            #filters: filters,
            #name: name,
            #relaySet: relaySet,
            #cacheRead: cacheRead,
            #cacheWrite: cacheWrite,
            #timeout: timeout,
            #timeoutCallbackUserFacing: timeoutCallbackUserFacing,
            #timeoutCallback: timeoutCallback,
            #explicitRelays: explicitRelays,
            #desiredCoverage: desiredCoverage,
          },
        ),
        returnValue: _FakeNdkResponse_1(
          this,
          Invocation.method(
            #query,
            [],
            {
              #filters: filters,
              #name: name,
              #relaySet: relaySet,
              #cacheRead: cacheRead,
              #cacheWrite: cacheWrite,
              #timeout: timeout,
              #timeoutCallbackUserFacing: timeoutCallbackUserFacing,
              #timeoutCallback: timeoutCallback,
              #explicitRelays: explicitRelays,
              #desiredCoverage: desiredCoverage,
            },
          ),
        ),
      ) as _i2.NdkResponse);

  @override
  _i2.NdkResponse subscription({
    required List<_i2.Filter>? filters,
    String? name = r'',
    String? id,
    _i2.RelaySet? relaySet,
    bool? cacheRead = false,
    bool? cacheWrite = false,
    Iterable<String>? explicitRelays,
    int? desiredCoverage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscription,
          [],
          {
            #filters: filters,
            #name: name,
            #id: id,
            #relaySet: relaySet,
            #cacheRead: cacheRead,
            #cacheWrite: cacheWrite,
            #explicitRelays: explicitRelays,
            #desiredCoverage: desiredCoverage,
          },
        ),
        returnValue: _FakeNdkResponse_1(
          this,
          Invocation.method(
            #subscription,
            [],
            {
              #filters: filters,
              #name: name,
              #id: id,
              #relaySet: relaySet,
              #cacheRead: cacheRead,
              #cacheWrite: cacheWrite,
              #explicitRelays: explicitRelays,
              #desiredCoverage: desiredCoverage,
            },
          ),
        ),
      ) as _i2.NdkResponse);

  @override
  _i3.Future<void> closeSubscription(
    String? subId, {
    String? debugLabel = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeSubscription,
          [subId],
          {#debugLabel: debugLabel},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> closeAllSubscription() => (super.noSuchMethod(
        Invocation.method(
          #closeAllSubscription,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i2.NdkResponse requestNostrEvent(_i2.NdkRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #requestNostrEvent,
          [request],
        ),
        returnValue: _FakeNdkResponse_1(
          this,
          Invocation.method(
            #requestNostrEvent,
            [request],
          ),
        ),
      ) as _i2.NdkResponse);
}

/// A class which mocks [NdkResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkResponse extends _i1.Mock implements _i2.NdkResponse {
  MockNdkResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get requestId => (super.noSuchMethod(
        Invocation.getter(#requestId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#requestId),
        ),
      ) as String);

  @override
  set requestId(String? _requestId) => super.noSuchMethod(
        Invocation.setter(
          #requestId,
          _requestId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Stream<_i2.Nip01Event> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.Nip01Event>.empty(),
      ) as _i3.Stream<_i2.Nip01Event>);

  @override
  _i3.Future<List<_i2.Nip01Event>> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i3.Future<List<_i2.Nip01Event>>.value(<_i2.Nip01Event>[]),
      ) as _i3.Future<List<_i2.Nip01Event>>);
}

/// A class which mocks [Nip01Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockNip01Event extends _i1.Mock implements _i2.Nip01Event {
  MockNip01Event() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get pubKey => (super.noSuchMethod(
        Invocation.getter(#pubKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#pubKey),
        ),
      ) as String);

  @override
  int get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: 0,
      ) as int);

  @override
  set createdAt(int? _createdAt) => super.noSuchMethod(
        Invocation.setter(
          #createdAt,
          _createdAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: 0,
      ) as int);

  @override
  List<List<String>> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <List<String>>[],
      ) as List<List<String>>);

  @override
  set tags(List<List<String>>? _tags) => super.noSuchMethod(
        Invocation.setter(
          #tags,
          _tags,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#content),
        ),
      ) as String);

  @override
  set content(String? _content) => super.noSuchMethod(
        Invocation.setter(
          #content,
          _content,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get sig => (super.noSuchMethod(
        Invocation.getter(#sig),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#sig),
        ),
      ) as String);

  @override
  set sig(String? _sig) => super.noSuchMethod(
        Invocation.setter(
          #sig,
          _sig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set validSig(bool? _validSig) => super.noSuchMethod(
        Invocation.setter(
          #validSig,
          _validSig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get sources => (super.noSuchMethod(
        Invocation.getter(#sources),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set sources(List<String>? _sources) => super.noSuchMethod(
        Invocation.setter(
          #sources,
          _sources,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isIdValid => (super.noSuchMethod(
        Invocation.getter(#isIdValid),
        returnValue: false,
      ) as bool);

  @override
  List<String> get tTags => (super.noSuchMethod(
        Invocation.getter(#tTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get pTags => (super.noSuchMethod(
        Invocation.getter(#pTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get replyETags => (super.noSuchMethod(
        Invocation.getter(#replyETags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toBase64() => (super.noSuchMethod(
        Invocation.method(
          #toBase64,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #toBase64,
            [],
          ),
        ),
      ) as String);

  @override
  void sign(String? privateKey) => super.noSuchMethod(
        Invocation.method(
          #sign,
          [privateKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getTags(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [tag],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String? getFirstTag(String? name) => (super.noSuchMethod(Invocation.method(
        #getFirstTag,
        [name],
      )) as String?);

  @override
  _i2.Nip01Event copyWith({
    String? pubKey,
    int? createdAt,
    int? kind,
    List<List<String>>? tags,
    String? content,
    String? sig,
    List<String>? sources,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #pubKey: pubKey,
            #createdAt: createdAt,
            #kind: kind,
            #tags: tags,
            #content: content,
            #sig: sig,
            #sources: sources,
          },
        ),
        returnValue: _FakeNip01Event_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #pubKey: pubKey,
              #createdAt: createdAt,
              #kind: kind,
              #tags: tags,
              #content: content,
              #sig: sig,
              #sources: sources,
            },
          ),
        ),
      ) as _i2.Nip01Event);
}

/// A class which mocks [NdkBroadcastResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkBroadcastResponse extends _i1.Mock implements _i2.NdkBroadcastResponse {
  MockNdkBroadcastResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Nip01Event get publishEvent => (super.noSuchMethod(
        Invocation.getter(#publishEvent),
        returnValue: _FakeNip01Event_2(
          this,
          Invocation.getter(#publishEvent),
        ),
      ) as _i2.Nip01Event);

  @override
  _i3.Future<List<_i5.RelayBroadcastResponse>> get broadcastDoneFuture => (super.noSuchMethod(
        Invocation.getter(#broadcastDoneFuture),
        returnValue:
            _i3.Future<List<_i5.RelayBroadcastResponse>>.value(<_i5.RelayBroadcastResponse>[]),
      ) as _i3.Future<List<_i5.RelayBroadcastResponse>>);

  @override
  _i3.Stream<List<_i5.RelayBroadcastResponse>> get broadcastDone => (super.noSuchMethod(
        Invocation.getter(#broadcastDone),
        returnValue: _i3.Stream<List<_i5.RelayBroadcastResponse>>.empty(),
      ) as _i3.Stream<List<_i5.RelayBroadcastResponse>>);
}
